version: '3.4'
services:
   angular_app:
      build:
         context: .
         target: setup
      image: angular_app
      container_name: angular_app
      ports:
         - "8090:80"
      restart: unless-stopped